BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS 'support_table' (
	'support_id'	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	'support_title'	TEXT,
	'support_text'	TEXT,
	'support_image'	TEXT
);
INSERT INTO 'support_table' VALUES (1,'Cymbal Anatomy','All drummers have a general idea on what cymbals are but not all of us know detailed information about cymbals. Our cymbal anatomy section gives you a detailed education on the basic anatomy of a cymbal, different cymbal types, characteristics of cymbals, and drumstick basics.','@drawable/support_anatomy');
INSERT INTO 'support_table' VALUES (2,'Cymbal Sound Classification System','Our classification system is a direct result of painstaking research. We thought very hard about how drummers and percussionists approach the idea of selecting cymbals. Learn more about the empirical and sound character of cymbals, the cymbal function and the general considerations for your cymbal choice.','@drawable/support_classification');
INSERT INTO 'support_table' VALUES (3,'Selecting & Testing','Selecting and testing cymbals can sometimes be a time consuming yet enjoyable task. But it is a very important process in finding your particular sound. Allow us to assist you with a few guidelines in selecting and choosing the ideal Paiste cymbal for you. Our guide to selecting and testing cymbals will become a very useful tool for you.','@drawable/support_selecting');
INSERT INTO 'support_table' VALUES (4,'Cymbal Usage & Care','If you treat your cymbals with the care and respect they deserve, you will be able to enjoy them for a very long time.','@drawable/support_usage');
INSERT INTO 'support_table' VALUES (5,'Cymbal Set Proposals','Some suggestions for you... in case you''re overwhelmed by so many choices.','@drawable/support_proposals');
INSERT INTO 'support_table' VALUES (6,'Warranty Information','Every PAISTE cymbal has a limited warranty of two years from the original date of purchase.','@drawable/support_warranty');
INSERT INTO 'support_table' VALUES (7,'Artist Endorsements','How do I become a Paiste Endorser?','@drawable/support_becomeendorser');

CREATE TABLE IF NOT EXISTS 'support_anatomy' (
	'anatomy_id'	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	'anatomy_title'	TEXT,
	'anatomy_subtitle'	TEXT,
	'anatomy_text'	TEXT
);
INSERT INTO 'support_anatomy' VALUES (1,'Bell','The bell is at the center of the cymbal.','Its shape and size affects the sound of the whole cymbal, and it is a useful playing area as it produces a separate type of sound, usually a clear tone, with a dominant higher pitch and sparse overtones. The bell can be used to play rhythmic figures or to accent such figures. It is normally played with the shank of the stick.');
INSERT INTO 'support_anatomy' VALUES (2,'Surface','The surface of the cymbal produces the majority of the cymbals vibration, and therefore its sound.','The surface produces a variety of sounds by playing different spots with the tip of the drumstick, with the shank of the drumstick, with brushes, or with mallets. Playing the surface in different areas can also vary the sound. Playing closer to the edge produces lower and fuller sound, while playing close to the bell produces higher and tighter sound.');
INSERT INTO 'support_anatomy' VALUES (3,'Edge','Striking the edge of the cymbal produces the cymbal’s fullest sound.','The edge is the most delicate part of the cymbal and great care should be taken not to damage it in any way.');
INSERT INTO 'support_anatomy' VALUES (4,'Taper','The taper is the gradual decrease in thickness from the bell to the edge.','Most cymbals are thinner toward edge. The whole curvature can also be pressed in, but we don’t do that.');
INSERT INTO 'support_anatomy' VALUES (5,'Curvature or Bow','(or Form, Shape)','Traditionally cymbals are hammered. Hammering compresses the metal, but also expands it sideways. This expansion causes the cymbal to become curved downward from the bell. The shape can vary from rather flat, which gives a lower pitch, to round, which gives a higher pitch.');
INSERT INTO 'support_anatomy' VALUES (6,'Ride','Ride cymbals are larger and usually thicker cymbals.','Which are mainly used for playing rhythmic figures on the surface and the bell, but they can also be crashed. Ride figures are the most prominent and colorful part of the overall rhythm created together with the bass drum and the snare. Ride cymbals usually build up less so one can play rhythmic patterns that will not get lost in the overall drum sound.');
INSERT INTO 'support_anatomy' VALUES (7,'Crash','Crashes are thinner and usually smaller cymbals.','Which are mainly used for creating accents by hitting them across the edge. Crash cymbals provide cymbal sound color. Crash cymbals are usually very responsive so that the full cymbal sound can occur quickly at the desired point in the musical phrase.');
INSERT INTO 'support_anatomy' VALUES (8,'Crash Ride','These are cymbals that combine ride and crash character.','Ride figures are still audible and useful but the overall sound of the cymbal is very lively, and crash accents will be full and usually quite energetic. We also refer to such cymbals as “Medium” or other designated models. Splash cymbals are very thin, small, and delicate cymbals that respond and fade quickly. Their main use is to set quick accents within the musical context.');
INSERT INTO 'support_anatomy' VALUES (9,'Hi-Hat','Hi-Hats are two paired cymbals.','Which are mounted opposite each other on a hi-hat stand. They can be closed or clashed together with a foot pedal. The top cymbal is usually thinner to make the hi-hat more responsive to stick work, and the two cymbals are usually quite different in sound. Hi-Hats can be played in a variety of ways: with the stick on the closed surface for distinct rhythmic patterns, half open on the surface or across the edge for full sounding rhythmic patterns. Closing the hi-hat rapidly produces the very short chick sound, which is used for rhythmic patterns, usually in context with ride, snare, and bass drum. They can also be clashed together to produce a crash sound.');
INSERT INTO 'support_anatomy' VALUES (10,'China or Swish','Chinese style cymbals, so named for their origin, feature an edge area that has a curvature opposite to the curvature of the main surface. ','The traditional edge is curved upward, so that often the cymbal is mounted upside down for easier playing. Paiste has introduced the downward turned edge to the china shape, so that the bell of the cymbal can be used well also. Chinas can be used for crashing or in larger sizes for riding. They are very versatile cymbals with a generally coarse, complex frequency mix, which is often thought of as exotic, oriental and trashy.');
INSERT INTO 'support_anatomy' VALUES (11,'Size','The larger a cymbal gets, the more volume it produces.','Also, the larger a cymbal of the same thickness gets, the lower its pitch will be. Larger cymbals generally sustain longer.');
INSERT INTO 'support_anatomy' VALUES (12,'Thickness','The thinner a cymbal gets, the more responsive it will be.','Also, the thicker a cymbal of the same size gets, the higher its pitch will be. Thicker cymbals generally sustain longer.');
INSERT INTO 'support_anatomy' VALUES (13,'Weight','Weight is the combination of size and thickness, and thus a relative and complex relationship.','Check the classification system for more detail.');
INSERT INTO 'support_anatomy' VALUES (14,'Bell Size','Bell size has to be considered relative to the overall cymbal size. ','Generally, cymbals with smaller bells will have a drier sound, and cymbals with larger bells are livelier.');
INSERT INTO 'support_anatomy' VALUES (15,'Curvature or Bow (or Form, Shape)','The profile or side view of the cymbal is the result of its curvature. ','A higher/rounder profile will result in a higher overall pitch.');
INSERT INTO 'support_anatomy' VALUES (16,'Tip','A larger tip has more body and contact with ','The type of the tip influences the sound color and character. In comparison, a wood tip produces a warmer, fuller, mellower, and darker sound, while a nylon tip produces a cooler, brighter, more focused sound.');
INSERT INTO 'support_anatomy' VALUES (17,'Size','The length and thickness of the drumstick influence ','A heavier stick (longer, thicker or both) will produce more volume and fuller sound. A lighter stick (shorter, thinner or both) will produce less volume and lighter sound.');
INSERT INTO 'support_anatomy' VALUES (18,'Stick Recommendations','The choice of drumstick is extremely personal. ','It should feel good in your hands and it should produce the type of sound you prefer. It is also a good idea to play more than one type of stick to achieve maximum variety with your cymbal sound. The weight of the stick should correspond to the sizes of your cymbals, so you should not play heavy sticks on smaller or thinner cymbals. There are alternatives to wood drumsticks, but we do not recommend them, because only wood has natural flexibility. Most alternative materials are too rigid and will cause you to weaken or break cymbals. Don’t use metal sticks on cymbals, as they are only meant for practicing purposes on a rubber pad.');
INSERT INTO 'support_anatomy' VALUES (19,'Sizzles / Rivets','Rivets add a pleasant silvery ring to the sustain of the cymbal. ','There are some things you should consider with rivets. The more sizzles you add to a cymbal, the drier the cymbal sound itself will become. Too many rivets can also have a negative effect on the cymbal’s even decay, hence it can stop itself, which appears „unnatural“. You should not drill holes too close to the edge of a cymbal or directly on the change of curvature in a china cymbal. Larger rivets or more rivets will produce more sizzle. Rivets made from brass produce a softer sizzle. Steel rivets produce a brighter, sharper sizzle. Consider having an expert install rivets or contact us for help.');
COMMIT;
